version: '2'
services:
  #MySQL
  db:
    image: mysql:latest
    env_file: .env
    volumes:
      - ./db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql

  #WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./themes:/var/www/html/wp-content/themes
